@echo off
setlocal
cd /d "%~dp0"
echo Building DF_Small...
call DF_Small\BUILD.cmd || exit /b 1
echo Building DF_Medium...
call DF_Medium\BUILD.cmd || exit /b 1
echo Building DF_Large...
call DF_Large\BUILD.cmd || exit /b 1
echo Building DF_Xtra_Large...
call DF_Xtra_Large\BUILD.cmd || exit /b 1
echo All node build commands completed.
